FIX: fix parallel doctests.
/me deserves a cookie!

The tests were failing because tutorial/extensions.rst was
contaminating mdp.nodes.SFANode with fake implementations
of _fork and other methods.

I'm adding a doctest SKIP flag to those examples. I'm also
changing 'return None' to 'return ...', because
- it'll be easier to diagnose in the feature if the doctest
  flag is lost ("EllipsisType has no attribute..." is better
  than "NoneType has no attribute...")
- it's more logical from the documentation p.o.v.: we want the
  function to return something, we're just too lazy to write it now

For reference, one of the failing doctests:
Document: tutorial/parallel
---------------------------
**********************************************************************
File "tutorial/parallel.rst", line ?, in default
Failed example:
    parallel_flow.train(data_iterables, scheduler=scheduler)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest default[8]>", line 1, in <module>
        parallel_flow.train(data_iterables, scheduler=scheduler)
      File "<string>", line 1, in <lambda>
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/extension.py", line 368, in wrapper
        result = func(*args, **kwargs)
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/parallel/parallelflows.py", line 355, in train
        self.use_results(results)
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/parallel/parallelflows.py", line 695, in use_results
        self._next_train_phase()
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/parallel/parallelflows.py", line 426, in _next_train_phase
        self._flownode.fork()
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/parallel/parallelnodes.py", line 59, in fork
        return self._fork()
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/parallel/parallelhinet.py", line 31, in _fork
        return self.__class__(self._flow.__class__(node_list))
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/linear_flows.py", line 104, in __init__
        self._check_nodes_consistency(flow)
      File "/home/zbyszek/mdp/mdp-toolkit-master/mdp/linear_flows.py", line 470, in _check_nodes_consistency
        inp = flow[i].input_dim
    AttributeError: 'NoneType' object has no attribute 'input_dim'